import type { Opening, Scene, SceneObject, Surface, Transform, Vec3 } from "@/scene/model/types";
import { pick } from "./materials";

/**
 * DEMONSTRATION SCENE — hand-authored, not the output of any analysis.
 *
 * A 6.0 × 4.8 m living room with two tall windows on the west wall and a
 * door in the north wall. It stands in for what the reconstruction pipeline
 * will eventually produce from a single photograph, so every value here has
 * the shape and plausibility of real output, but none of it is measured.
 */

export const place = (position: Vec3, rotationY = 0): Transform => ({
  position,
  rotation: [0, rotationY, 0],
  scale: [1, 1, 1],
});

const ROOM_HEIGHT = 2.8;

export const livingRoomSurfaces: Surface[] = [
  { id: "floor", kind: "floor", label: "Floor", materialId: "oak-floor", evidence: "observed" },
  { id: "ceiling", kind: "ceiling", label: "Ceiling", materialId: "paint-white", evidence: "observed" },
  {
    id: "wall-north",
    kind: "wall",
    label: "North wall",
    materialId: "paint-white",
    evidence: "observed",
    start: [-3, -2.4],
    end: [3, -2.4],
    thickness: 0.16,
  },
  {
    id: "wall-west",
    kind: "wall",
    label: "West wall",
    materialId: "paint-white",
    evidence: "observed",
    start: [-3, 2.4],
    end: [-3, -2.4],
    thickness: 0.16,
  },
  {
    // Outside the photograph's frame: completed by inference.
    id: "wall-east",
    kind: "wall",
    label: "East wall",
    materialId: "paint-white",
    evidence: "inferred",
    start: [3, -2.4],
    end: [3, 2.4],
    thickness: 0.16,
  },
];

export const livingRoomOpenings: Opening[] = [
  {
    id: "window-south",
    kind: "window",
    label: "Window",
    wallId: "wall-west",
    offset: 1.35,
    width: 1.25,
    height: 2.1,
    sill: 0.42,
    frameMaterialId: "frame-white",
    panelMaterialId: "glass-clear",
  },
  {
    id: "window-north",
    kind: "window",
    label: "Window",
    wallId: "wall-west",
    offset: 3.3,
    width: 1.25,
    height: 2.1,
    sill: 0.42,
    frameMaterialId: "frame-white",
    panelMaterialId: "glass-clear",
  },
  {
    id: "door",
    kind: "door",
    label: "Door",
    wallId: "wall-north",
    offset: 4.95,
    width: 0.9,
    height: 2.1,
    sill: 0,
    frameMaterialId: "frame-white",
    panelMaterialId: "frame-white",
  },
];

const objects: SceneObject[] = [
  {
    id: "sofa",
    category: "sofa",
    label: "Sofa",
    form: "track-arm",
    transform: place([-0.85, 0, -1.9]),
    dimensions: [2.3, 0.8, 0.96],
    materials: { upholstery: "linen-oat", legs: "walnut" },
    support: { kind: "floor" },
  },
  {
    id: "cushions",
    category: "cushion",
    label: "Cushions",
    form: "pair",
    transform: place([-0.85, 0.44, -2.14]),
    dimensions: [1.7, 0.42, 0.16],
    materials: { cover: "linen-oat" },
    support: { kind: "object", objectId: "sofa" },
  },
  {
    id: "artwork",
    category: "artwork",
    label: "Artwork",
    form: "framed-print",
    transform: place([-0.85, 1.3, -2.4]),
    dimensions: [0.95, 0.72, 0.035],
    materials: { frame: "walnut", surface: "print-paper" },
    support: { kind: "wall", wallId: "wall-north" },
  },
  {
    id: "coffee-table",
    category: "coffee-table",
    label: "Coffee table",
    form: "slab",
    transform: place([-0.7, 0, -0.6]),
    dimensions: [1.2, 0.38, 0.64],
    materials: { top: "marble", legs: "steel-black" },
    support: { kind: "floor" },
  },
  {
    id: "vase",
    category: "vase",
    label: "Vase",
    form: "bottle",
    transform: place([-0.98, 0.38, -0.55]),
    dimensions: [0.15, 0.28, 0.15],
    materials: { body: "ceramic-white" },
    support: { kind: "object", objectId: "coffee-table" },
  },
  {
    id: "books",
    category: "books",
    label: "Books",
    form: "stack",
    transform: place([-0.42, 0.38, -0.66], 0.2),
    dimensions: [0.3, 0.1, 0.22],
    materials: { cover: "book-covers" },
    support: { kind: "object", objectId: "coffee-table" },
  },
  {
    id: "rug",
    category: "rug",
    label: "Rug",
    form: "rect",
    transform: place([-0.75, 0, -0.85]),
    dimensions: [2.8, 0.012, 2.0],
    materials: { pile: "wool-rug" },
    support: { kind: "floor" },
  },
  {
    id: "armchair",
    category: "armchair",
    label: "Armchair",
    form: "club",
    transform: place([-2.05, 0, 0.75], 2.2),
    dimensions: [0.82, 0.76, 0.84],
    materials: { upholstery: "leather-cognac", legs: "walnut" },
    support: { kind: "floor" },
  },
  {
    id: "ottoman",
    category: "ottoman",
    label: "Ottoman",
    form: "round",
    transform: place([-1.35, 0, 0.3]),
    dimensions: [0.5, 0.4, 0.5],
    materials: { cover: "leather-cognac" },
    support: { kind: "floor" },
  },
  {
    id: "side-table",
    category: "side-table",
    label: "Side table",
    form: "round",
    transform: place([-2.35, 0, -1.95]),
    dimensions: [0.46, 0.52, 0.46],
    materials: { top: "walnut" },
    support: { kind: "floor" },
  },
  {
    id: "floor-lamp",
    category: "floor-lamp",
    label: "Floor lamp",
    form: "tripod",
    transform: place([0.55, 0, -2.0]),
    dimensions: [0.46, 1.6, 0.46],
    materials: { shade: "linen-shade", stand: "walnut" },
    support: { kind: "floor" },
  },
  {
    id: "basket",
    category: "basket",
    label: "Basket",
    form: "round",
    transform: place([0.55, 0, -1.3]),
    dimensions: [0.38, 0.4, 0.38],
    materials: { weave: "jute" },
    support: { kind: "floor" },
  },
  {
    id: "pendant-lamp",
    category: "pendant-lamp",
    label: "Pendant",
    form: "dome",
    transform: place([-0.7, 1.95, -0.6]),
    dimensions: [0.46, ROOM_HEIGHT - 1.95, 0.46],
    materials: { shade: "steel-black", diffuser: "linen-shade" },
    support: { kind: "ceiling" },
  },
  {
    id: "plant",
    category: "plant",
    label: "Plant",
    form: "fiddle-leaf",
    transform: place([-2.62, 0, 0.05]),
    dimensions: [0.6, 1.55, 0.6],
    materials: { pot: "ceramic-white", foliage: "leaf", stem: "walnut" },
    support: { kind: "floor" },
  },
];

export const livingRoom: Scene = {
  schemaVersion: 1,
  id: "demo-living-room",
  provenance: {
    kind: "demo",
    description: "Hand-authored demonstration scene. No photograph was analysed to produce it.",
  },
  room: {
    type: "living-room",
    label: "Living room",
    footprint: [
      [-3, -2.4],
      [3, -2.4],
      [3, 2.4],
      [-3, 2.4],
    ],
    height: ROOM_HEIGHT,
  },
  camera: {
    position: [2.25, 1.32, 2.2],
    target: [-1.15, 0.98, -1.2],
    verticalFov: 52,
    aspect: 3 / 2,
  },
  surfaces: livingRoomSurfaces,
  openings: livingRoomOpenings,
  objects,
  materials: pick(
    "paint-white",
    "oak-floor",
    "frame-white",
    "glass-clear",
    "steel-black",
    "linen-oat",
    "wool-rug",
    "jute",
    "leather-cognac",
    "walnut",
    "marble",
    "ceramic-white",
    "linen-shade",
    "print-paper",
    "book-covers",
    "leaf",
  ),
  lights: [
    {
      id: "daylight",
      kind: "daylight",
      label: "Window light",
      openingIds: ["window-south", "window-north"],
      // Early afternoon, which is the light the room is described in.
      timeOfDay: 0.18,
    },
    { id: "ambient", kind: "ambient", label: "Ambient light", color: "#e9e4dc" },
    {
      id: "light-floor-lamp",
      kind: "artificial",
      label: "Floor lamp",
      fixtureId: "floor-lamp",
      emitterOffset: [0, 1.42, 0],
      colorTemperature: 2700,
    },
    {
      id: "light-pendant",
      kind: "artificial",
      label: "Pendant",
      fixtureId: "pendant-lamp",
      emitterOffset: [0, 0.12, 0],
      colorTemperature: 2700,
    },
  ],
  relationships: [
    { id: "r1", subjectId: "sofa", predicate: "against", objectId: "wall-north" },
    { id: "r2", subjectId: "artwork", predicate: "above", objectId: "sofa" },
    { id: "r3", subjectId: "cushions", predicate: "on", objectId: "sofa" },
    { id: "r4", subjectId: "coffee-table", predicate: "in-front-of", objectId: "sofa" },
    { id: "r5", subjectId: "rug", predicate: "under", objectId: "coffee-table" },
    { id: "r6", subjectId: "vase", predicate: "on", objectId: "coffee-table" },
    { id: "r7", subjectId: "books", predicate: "on", objectId: "coffee-table" },
    { id: "r8", subjectId: "pendant-lamp", predicate: "above", objectId: "coffee-table" },
    { id: "r9", subjectId: "side-table", predicate: "beside", objectId: "sofa" },
    { id: "r10", subjectId: "floor-lamp", predicate: "beside", objectId: "sofa" },
    { id: "r11", subjectId: "basket", predicate: "beside", objectId: "floor-lamp" },
    { id: "r12", subjectId: "armchair", predicate: "faces", objectId: "sofa" },
    { id: "r13", subjectId: "ottoman", predicate: "in-front-of", objectId: "armchair" },
    { id: "r14", subjectId: "armchair", predicate: "beside", objectId: "window-south" },
    { id: "r15", subjectId: "plant", predicate: "beside", objectId: "window-north" },
    { id: "r16", subjectId: "sofa", predicate: "lit-by", objectId: "daylight" },
    { id: "r17", subjectId: "rug", predicate: "under", objectId: "sofa" },
  ],
};
